### ISSUE TITLE
Automatically load conda packages from the dependend julia packages 

### ISSUE THREAD

**Issue by schlichtanders** [JuliaPy/CondaPkg.jl#111]
Hello,

I am starting to use PythonCall and CondaPkg more extensively. The setup looks awesomely analogous to how Julia packages are handled with Project.toml files.

However, while Project.toml files are resolved recursively in that the dependencies of the dependencies are also taken into account, CondaPkg does not seem to pick up the CondaPkg.toml from one of my loaded Packages.
Maybe I am just missing something.

--------------------

EDIT: 
my setup is very simple:
- `MyPackage` has a CondaPkg.toml at top-level (with `dill` added as a dependency)
- I am starting julia in the default `v1.9` environment and hit `using MyPackage, PythonCall; pyimport("dill")`

I was now expecting that CondaPkg will load also the information from MyPackage/CondaPkg.toml. Instead I get the error
```julia
julia> pyimport("dill")
ERROR: Python: ModuleNotFoundError: No module named 'dill'
Python stacktrace: none
Stacktrace:
 [1] pythrow()
   @ PythonCall ~/.julia/packages/PythonCall/1f5yE/src/err.jl:94
 [2] errcheck
   @ ~/.julia/packages/PythonCall/1f5yE/src/err.jl:10 [inlined]
 [3] pyimport(m::String)
   @ PythonCall ~/.julia/packages/PythonCall/1f5yE/src/concrete/import.jl:11
 [4] top-level scope
   @ REPL[10]:1
```

**Comment by cjdoris** [comment]
CondaPkg only reads the CondaPkg.toml file from packages which actually depend on CondaPkg. So you need to `Pkg.add("CondaPkg")` in `MyPackage`.

**Comment by schlichtanders** [comment]
Indeed I was only depending on PythonCall - awesome that this is already supported!

**Comment by schlichtanders** [comment]
worked :smiley_cat:
