### ISSUE TITLE
How to make RCall.jl use a CondaPkg.jl environment?

### ISSUE THREAD

**Issue by schlichtanders** [JuliaPy/CondaPkg.jl#113]
Hi,
this package is really really awesome! :)

I would like to also use RCall on top of it, however for this I seem to need `Conda.jl`. Hence I would like to let it make Conda.jl use my current CondaPkg.jl environment.

Conda.jl documentation tells:
1. set `ENV["CONDA_JL_HOME"]` to the environment (which will become Conda.jl root environment, which should be the one picked up by RCall / PyCall)
2. set `ENV["CONDA_JL_CONDA_EXE"]` to the executable in order to not install two different condas
3. rebuild Conda.jl and respective dependencies

My status:
- [x] 1. I guess this is corresponds to CondaPkg.jl `ENV["JULIA_CONDAPKG_ENV"]`, which I already set
- [x] 2. I guess this is corresponds to `CondaPkg.MicroMamba.executable()`
- [x] 3. rebuilding is okay for me, because I am using a fixed conda environment per julia process

So it happens by writing this issue, I have solved kind of a couple of steps myself :)
Maybe someone can check whether this makes sense, or whether I overlooked something.

I will try it out myself soon and report in this issue.

**Comment by schlichtanders** [comment]
Short remark: When simple using R, it is probably sufficient to just set
```julia
ENV["R_HOME"] = CondaPkg.envdir() * "/lib/R"
```
and rebuild RCall (Probably a similar approach also works for PyCall)

**Comment by schlichtanders** [comment]
I tried running the following
```julia
julia> using CondaPkg

julia>

julia> ENV["R_HOME"] = CondaPkg.envdir() * "/lib/R"

julia> import Pkg

julia> Pkg.build("RCall")

julia> import RCall
┌ Warning: RCall.jl: During startup - Warning messages:
│ 1: package ‘utils’ in options("defaultPackages") was not found 
│ 2: package ‘stats’ in options("defaultPackages") was not found 
└ @ RCall ~/.julia/packages/RCall/gOwEW/src/io.jl:172
```

The CondaPkg environment does not have a proper R setup... I am confused. Any help is highly appreciated

**Comment by schlichtanders** [comment]
@simonbyrne maybe you can help?

**Comment by simonbyrne** [comment]
Unfortunately, I'm afraid I haven't looked at RCall.jl for some time, and my bandwidth is rather limited at the moment.

**Comment by cjdoris** [comment]
Perhaps you need to activate the Conda environment in your Julia session first like PythonCall does here: https://github.com/JuliaPy/PythonCall.jl/blob/0056de8711e274b3d8084d19a23fe54adf5d0640/src/cpython/context.jl#L68

**Comment by schlichtanders** [comment]
Thank you for your comments. It turned out it was a linux distribution specific problem which is already [reported at anaconda](https://github.com/ContinuumIO/anaconda-issues/issues/11133). Concretely you need to have `/usr/bin/which` available on your system for R...

It works now that I've symlinked `/usr/bin/which`

**Comment by schlichtanders** [comment]
related issue: https://github.com/JuliaInterop/RCall.jl/issues/480 (tries to improve RCall.jl for better integration with CondaPkg.jl without the need of `Pkg.build("RCall")`)

**Comment by schlichtanders** [comment]
> Short remark: When simple using R, it is probably sufficient to just set
> 
> ```julia
> ENV["R_HOME"] = CondaPkg.envdir() * "/lib/R"
> ```
> 
> and rebuild RCall (Probably a similar approach also works for PyCall)

this is the final way I am using
```julia
import CondaPkg
ENV["R_HOME"] = CondaPkg.envdir() * "/lib/R"
import Pkg
Pkg.build("RCall")
using RCall
```
