### ISSUE TITLE
[Bug] file is not passed to write_toml

### ISSUE THREAD

**Issue by schlichtanders** [JuliaPy/CondaPkg.jl#118]
I just read through the code because I want to manipulate the toml without installing packages and saw that there is a tiny bug in how the `file` keyword argument is forwarded

https://github.com/JuliaPy/CondaPkg.jl/blob/main/src/deps.jl#L215-L224

```diff
function add(pkgs::AbstractVector; resolve=true, file=cur_deps_file(), kw...)
    toml = read_deps(; file)
    for pkg in pkgs
        add!(toml, pkg)
    end
-   write_deps(toml)
+   write_deps(toml; file)
    STATE.resolved = false
    resolve && CondaPkg.resolve(; kw...)
    return
end
```

**Comment by cjdoris** [comment]
Thanks - I happened to be at my computer so fixed it immediately.

**Comment by schlichtanders** [comment]
thank you too - that was really fast :slightly_smiling_face:
