### ISSUE TITLE
using CondaPkg with Pluto leads to unnecesarry resolves

### ISSUE THREAD

**Issue by schlichtanders** [JuliaPy/CondaPkg.jl#120]
Hi

I am integrating CondaPkg with Pluto and realized that I have a lot of overhead everytime I start a new Pluto notebook despite all condapkg already being installed.

I debugged it a bit and saw that it is due to a meta file which, if it is missing, triggers a complete reinstall.

The situation for me is that Pluto always creates a fresh new Julia environment (temporary) when opening a notebook. The CondaPkg.toml will be written into it.
- there is no meta file written initially
- I am preserving the conda environment via `JULIA_CONDAPKG_ENV` environment variable, hence the package are indeed preserved and can be found by conda

I think two steps would be needed to make the conda resolve work in such Pluto scenario:
1. place the meta file inside the conda environment instead of the julia environment
2. make the meta file check not compare creation times of CondaPkg.toml and the meta file (this would still invalidate), but rather use a hash of the CondaPkg.toml file

What do you think?

**Comment by schlichtanders** [comment]
@cjdoris I have resource to create a pullrequest. Would you like to have this changed?

**Comment by schlichtanders** [comment]
My current thought is that it might be the better approach to extend Pluto with a feature to preserve environments.

**Comment by schlichtanders** [comment]
> My current thought is that it might be the better approach to extend Pluto with a feature to preserve environments.

this was much simpler and already worked out.

**Comment by stillyslalom** [comment]
@schlichtanders what solution did you arrive at? I'm using Preferences.jl to set a shared Conda environment by default for a package, but the preference is ignored by Pluto, which leads to a minute or more of Conda resolve time upon notebook creation.

**Comment by schlichtanders** [comment]
I have my own fork of Pluto where I now create a hashed project directory instead of a random one.
This way I am resolving this issue. Unfortunately I haven't found a workaround without changing Pluto

**Comment by stillyslalom** [comment]
Do you know if there's already an issue filed in the Pluto repo? I couldn't find one, but I'll create one if it doesn't exist.

**Comment by schlichtanders** [comment]
I haven't created one. But I probably could extract some parts of my fork in order to solve a respective issue. Can't promise how much time I have though
