### ISSUE TITLE
`pip_add` for URLs

### ISSUE THREAD

**Issue by fivegrant** [JuliaPy/CondaPkg.jl#124]
Currently `pip_add` doesn't allow users to install from a URL which is a common use case. Additionally, installing from a URL with pip allows you to optionally select a revision or tag.

**Comment by Dale-Black** [comment]
This would be useful to me too, but I know everyone's time is limited. Just want to +1 this

**Comment by cjdoris** [comment]
Can't you do `pip_add foo@https://whatever.com/foo`?

**Comment by Dale-Black** [comment]
How would that look for the [segment-anything repo](https://arc.net/l/quote/yagcpnfc) for example?

```julia
begin
	using Pkg; Pkg.activate(temp = true)
	Pkg.add("CondaPkg")
	using CondaPkg
	CondaPkg.add_pip("git+https://github.com/facebookresearch/segment-anything.git")
end
```

**Comment by Dale-Black** [comment]
And neither does this

```julia
begin
	using Pkg; Pkg.activate(temp = true)
	Pkg.add("CondaPkg")
	using CondaPkg
	CondaPkg.add_pip("segment-anything@https://github.com/facebookresearch/segment-anything")
end
```

**Comment by Dale-Black** [comment]
Ohhhh this works
```
conda pip_add segment-anything@git+https://github.com/facebookresearch/segment-anything.git
```

**Comment by cjdoris** [comment]
You can do the same with `add_pip` too like this:
```julia
CondaPkg.add_pip("segment-anything", version="@https://github.com/facebookresearch/segment-anything")
```

I have added an [FAQ](https://github.com/JuliaPy/CondaPkg.jl?tab=readme-ov-file#can-i-install-a-package-from-a-url-or-file) to the readme.
