### ISSUE TITLE
pin openssl to a compatible version

### ISSUE THREAD

**Issue by cjdoris** [JuliaPy/CondaPkg.jl#138]
Similar what we do for libstdc++, provide a mechanism to depend on openssl at a version compatible with whatever is used by Julia.

**Comment by cjdoris** [comment]
c.f. https://github.com/JuliaPy/PythonCall.jl/issues/519

**Comment by untoreh** [comment]
OpenSSL_jll supports openssl 3.2 but CondaPkg pins it to 3.0. I was using openssl=3.2 in my `CondaPkg.toml`. I am using the default conda `libmamba` and now it fails to resolve

**Comment by JordiBolibar** [comment]
I'm currently running into this issue, my environment needs:

```
error    libmamba Could not solve for environment specs
    The following packages are incompatible
    ├─ openssl 3.3.1  is requested and can be installed;
    └─ openssl >=3,<3.1  is not installable because it conflicts with any installable versions previously reported.
critical libmamba Could not solve for environment specs
```
But `openssl` is pinned to a too restrictive range. 

More details here: https://discourse.julialang.org/t/inconsistent-condapkg-environments/118767/5

**Comment by cjdoris** [comment]
Closing as the original issue is solved. @JordiBolibar I'll respond to your discourse post.
