### ISSUE TITLE
Support for uv Backend?

### ISSUE THREAD

**Issue by andrew-saydjari** [JuliaPy/CondaPkg.jl#149]
I have been a loyal CondaPkg.jl user for a while, and I love that I can use MicroMamba (and pip as needed) for the package resolution. I have recently gotten a lot of recommendations for https://github.com/astral-sh/uv to do the package resolution. Are there any thoughts/plans on adding this as a package resolution manager here (or elsewhere)?

**Comment by cjdoris** [comment]
It's already optionally supported - if you have `uv` as a dependency in any CondaPkg.toml file then it will be used instead of `pip` to install any pip dependencies.

I'm considering making it always use `uv`, with an option to choose `pip` instead.

**Comment by andrew-saydjari** [comment]
Amazing! Happy to close the issue or leave it open as a placeholder to get this fact into the documentation (which I don't think is there, unless I missed it).

**Comment by cjdoris** [comment]
You can now control this behaviour with the `pip_backend` preference - see [the readme](https://github.com/JuliaPy/CondaPkg.jl?tab=readme-ov-file#pip-backends). It is `uv` by default now. Will appear in the next release.

**Comment by andrew-saydjari** [comment]
I just want to note that in during the runtest in this CI, [test](https://github.com/andrew-saydjari/ApogeeReduction.jl/actions/runs/11282243977/job/31379288622), the install from the CondaPkg.jl proceeds via micromamba. Is this unavoidable since we need to do at least one mamba/conda run to get pip/uv? I also will note that it downloaded pip rather than uv, which confused me based on the above discussion, but I am probably missing something in my CI set up?
